### ISSUE TITLE
Unknown GPU

### ISSUE THREAD

**Issue by NdranC** [MiMillieuh/Photoshop-CC2022-Linux#22]
![image](https://user-images.githubusercontent.com/27837113/169661896-8887db3e-2d61-47e3-b99b-b990f5742a78.png)
This is the performance tab on your version of Photoshop CC2022

![image](https://user-images.githubusercontent.com/27837113/169661934-36a8bd9f-3fe9-466d-a2c4-8391bb692745.png)
This is what it looks like on another version (CC2019) under the same system

Is this a bug that my gpu doesn't show up or is it intended with your version?

**Comment by YoungFellow-le** [comment]
To use your GPU, you must have Vulkan installed in your prefix,
Download the [setup_vkd3d_proton.sh](https://github.com/HansKristian-Work/vkd3d-proton/blob/master/setup_vkd3d_proton.sh) file, and then run:
```
WINEPREFIX="path/to/the/prefix" sh setup_vkd3d_proton.sh install
```
In my case, I found it to be too problematic, so I made it optional in [my fork](https://github.com/YoungFellow-le/Linux-PhotoshopCC-v22).

**Comment by MiMillieuh** [comment]
> To use your GPU, you must have Vulkan installed in your prefix,
> Download the [setup_vkd3d_proton.sh](https://github.com/HansKristian-Work/vkd3d-proton/blob/master/setup_vkd3d_proton.sh) file, and then run:
> ```bash
> # To install:
> 
> WINEPREFIX="path/to/the/prefix" sh setup_vkd3d_proton.sh install
> 
> # To uninstall:
> 
> WINEPREFIX="path/to/the/prefix" sh setup_vkd3d_proton.sh uninstall
> ```
> In my case, I found it to be too problematic, so I made it optional in [my fork](https://github.com/YoungFellow-le/Linux-PhotoshopCC-v22). 

Vulkan doesn't work with CC 2022

**Comment by MiMillieuh** [comment]
> > To use your GPU, you must have Vulkan installed in your prefix,
> > Download the [setup_vkd3d_proton.sh](https://github.com/HansKristian-Work/vkd3d-proton/blob/master/setup_vkd3d_proton.sh) file, and then run:
> > ```bash
> > # To install:
> > 
> > WINEPREFIX="path/to/the/prefix" sh setup_vkd3d_proton.sh install
> > 
> > # To uninstall:
> > 
> > WINEPREFIX="path/to/the/prefix" sh setup_vkd3d_proton.sh uninstall
> > ```
> > In my case, I found it to be too problematic, so I made it optional in [my fork](https://github.com/YoungFellow-le/Linux-PhotoshopCC-v22). 
> 
> Vulkan doesn't work with CC 2022 
> 
> So it's currently disabled on 2022
> 
> If you want gpu acceleration you can use the 2021 version

If you do like he said your PS installation will be broken

**Comment by MiMillieuh** [comment]
Update : I can get GPU detected but still not usable

**Comment by Arecsu** [comment]
Great progress @MiMillieuh. How's going so far? Do you have any ideas regarding why Photoshop 2022 have problems with the GPU compared to 2021? Just being curious. I've just found out about this repo and I'm about to test PS 2021

**Comment by MiMillieuh** [comment]
> Great progress @MiMillieuh. How's going so far? Do you have any ideas regarding why Photoshop 2022 have problems with the GPU compared to 2021? Just being curious. I've just found out about this repo and I'm about to test PS 2021

I don't really know why... it might be related to dxvk and vkd3d. I'm trying to find a patch for wine to fix these issues.

**Comment by Arecsu** [comment]
There was a thread in Adobe Official Forums where people were getting the same error of Unknown GPU on Windows. Can't recall the version, but the thread was from June 2021.

What's funny is that one of the fixes for many of them was to reinstall Photoshop but using the language English (international). Other languages gave them these unknown gpu problem, even with English EEUU.

I've noticed that your Photoshop uses English UK. I mean, I don't really think this fix applies here but... I guess we should try? I can't do it given I dont exactly know how this Photoshop for linux is packaged tbh, but if you could it would be awesome.

Also, latest version of Photoshop dropped support of DX11 and it uses DX12. Any GPU thats not DX12 wont work. Maybe there's something related to vkd3d. I couldn't make it work either. The logs in the terminal while running Photoshop dont help that much. Photoshop itself says that the GPU doesnt support DX12 but it detects support for OpenCL and OpenGL. It also throws 1500mb vram, given that I have a 8gb gpu (nvidia 2070s). PS 2022 requires a minimum of 2gb to work.

**Comment by MiMillieuh** [comment]
> There was a thread in Adobe Official Forums where people were getting the same error of Unknown GPU on Windows. Can't recall the version, but the thread was from June 2021.
> 
> What's funny is that one of the fixes for many of them was to reinstall Photoshop but using the language English (international). Other languages gave them these unknown gpu problem, even with English EEUU.
> 
> I've noticed that your Photoshop uses English UK. I mean, I don't really think this fix applies here but... I guess we should try? I can't do it given I dont exactly know how this Photoshop for linux is packaged tbh, but if you could it would be awesome.
> 
> Also, latest version of Photoshop dropped support of DX11 and it uses DX12. Any GPU thats not DX12 wont work. Maybe there's something related to vkd3d. I couldn't make it work either. The logs in the terminal while running Photoshop dont help that much. Photoshop itself says that the GPU doesnt support DX12 but it detects support for OpenCL and OpenGL. It also throws 1500mb vram, given that I have a 8gb gpu (nvidia 2070s). PS 2022 requires a minimum of 2gb to work.
> 
> On 7 Jul 2022, 23:01 -0300, MiMillieuh ***@***.***>, wrote:
> > > Great progress @MiMillieuh. How's going so far? Do you have any ideas regarding why Photoshop 2022 have problems with the GPU compared to 2021? Just being curious. I've just found out about this repo and I'm about to test PS 2021
> > I don't really know why... it might be related to dxvk and vkd3d. I'm trying to find a patch for wine to fix these issues.
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you commented.Message ID: ***@***.***>
> 

I've already tried these kind of solutions from the forums. They didn't work... it's related to dxvk and vkd3d. And dxvk is required because even if photoshop dropped dx11, it still use some of the old libraries. 

Also my computer is far from photoshop's minimal requirements... (I just have 512mb of vram). But in a windows environment it will work but will just throw a waring message. 

The problem won't happen in a windows environment so it won't be fixed by anything that could be found on adobe forums. (At least it could give some information but the fix will be different.)

**Comment by Arecsu** [comment]
I've made some progress!

![Screenshot from 2022-07-08 15-55-49](https://user-images.githubusercontent.com/12679098/178054686-c42dbe38-3868-4165-8f42-00a4ec0948f7.png)

I'm using latest Fedora Workstation release. Installed Lutris, created an app with the already installed Photoshop version of your script with the same wine prefix and folders. Just the default options with the latest versions of Wine, VKD3D and DXVK. No FSYNC.

It now detects the GPU but when trying to create a new document it crashes. I'll continue to find a way to make it work.

![Screenshot from 2022-07-08 15-57-00](https://user-images.githubusercontent.com/12679098/178054718-58d52141-a751-4556-8230-cf4db39bc4a5.png)

**Comment by Arecsu** [comment]
Small update: deactivating Native Canvas in Photoshop preferences works :)

Liquify still doesn't work and crashes the entire app. Basic functionality is working so far. Needs further testing.

![Screenshot from 2022-07-08 16-06-22](https://user-images.githubusercontent.com/12679098/178055186-c952a06d-b28e-44ef-aab6-b65cf9ef8e42.png)

**Comment by Arecsu** [comment]
Update: liquify works now :)

[wine-tkg-git](https://github.com/Frogging-Family/wine-tkg-git) have the patches needed for childwindow to work. I've used the latest nightly build available for Fedora, unzip it in `~/.local/share/lutris/runners/wine/` and made sure to give `chmod -x *` to all the files in the folder `bin/`

Changed the runner in Lutris to that one and... bam! Fsync works as well

![Screenshot from 2022-07-08 17-36-51](https://user-images.githubusercontent.com/12679098/178066776-8f2411b1-09d1-4f2f-b73e-d11365ee02fe.png)

A bit buggy nonetheless but usable! Resizing the Liquify window will bug it even more

**Comment by MiMillieuh** [comment]
Hello, I've modified the installer with your suggestions. 
To be fair my computer can't handle PS2022 (it doesn't have the requirements so I'm stuck with CC2021).
If you want you can try to use it.
https://raw.githubusercontent.com/MiMillieuh/Photoshop-CC2022-Linux/main/scripts/photoshop2022install.sh
It should work like the old one. (run `sh photoshop2022install.sh /path/to/a/dir`)
I can't try it by myself.

**Comment by Arecsu** [comment]
Thank you @MiMillieuh.

I'm testing it. So far, works very similar to your CC2021. 

- Object selector tool doesn't work (it didn't in Lutris either). Don't know if that tool worked in 2021. Seems related to a library or windows call missing that OpenCV needs.
- Liquify throws the same error as CC2021 related to the disk. Seems like a library that's being replaced by Lutris or something made it work there.

Best shot would be to keep using CC2021 for now after all. I should test if CC2021 performs better under Lutris.

**Comment by MiMillieuh** [comment]
> Thank you @MiMillieuh.
> 
> I'm testing it. So far, works very similar to your CC2021. 
> 
> - Object selector tool doesn't work (it didn't in Lutris either). Seems related to a library or windows call missing that OpenCV needs. Works on CC2021
> - Liquify throws the same error as CC2021 related to the disk. Seems like a library that's being replaced by Lutris or maybe these specific versions made it to work:
>   
>   - DXVK v1.10.1
>   - VKD3D v2.6
>   - D3D Extras v2
> 
> Liquify definitely needs [wine-tkg-git](https://github.com/Frogging-Family/wine-tkg-git) to work.
> 
> Best shot would be to keep using CC2021 for now after all.
> 
The CC2021 version has the selector tool working. In my case CC2021 has most of the functions working. (I don't use liquify so I don't really mind but maybe I can try to bundle this wine with it too)

I guess lutris does something more because I've included the wine tkg... 

I'll try something else this afternoon but yeah it's complicated since I have to do it blindly

**Comment by MiMillieuh** [comment]
Closed for inactivity
